PORT = 8080
BUFFER_WIDTH = 384
BUFFER_HEIGHT = 224
BUFFER_BPP = 3
BUFFER_SIZE = BUFFER_WIDTH * BUFFER_HEIGHT * BUFFER_BPP

HP_BAR_WIDTH = 160
HP_BAR_HEIGHT = 1
HP_BAR_OFFSET_X = 8
HP_BAR_OFFSET_Y = 20 # 18 is bar's upper bound + 2 to get to the middle row

P1_HP_BAR_REGION = (
    HP_BAR_OFFSET_X, 
    HP_BAR_OFFSET_Y, 
    HP_BAR_OFFSET_X + HP_BAR_WIDTH,
    HP_BAR_OFFSET_Y + HP_BAR_HEIGHT
)

P2_HP_BAR_REGION = (
    BUFFER_WIDTH - HP_BAR_OFFSET_X - HP_BAR_WIDTH, 
    HP_BAR_OFFSET_Y, 
    BUFFER_WIDTH - HP_BAR_OFFSET_X,
    HP_BAR_OFFSET_Y + HP_BAR_HEIGHT
)

HP_GREEN = (16, 255, 0)
HP_YELLOW = (255, 255, 0)
HP_ORANGE = (255, 198, 0)
HP_COLORS = {HP_GREEN, HP_YELLOW, HP_ORANGE}

HP_MAX = HP_BAR_WIDTH
